[package]
name = "github-clone-org"
version = "0.1.0"
authors = ["Daniel <30466471+daniel0611@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.2.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "^0.11.0", features = ["json"] }
serde = { version = "^1.0.118", features = ["derive"] }
git2 = "^0.13.15"
clap = "3.0.0-beta.2"

[dev-dependencies]
tempfile = "^3.2.0"